// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM55-jJLkMQ2jWM5gvWmqtoRe8oDsPbws',
    appId: '1:842796006174:web:63712054497a2d0742e70f',
    messagingSenderId: '842796006174',
    projectId: 'students-database-49778',
    authDomain: 'students-database-49778.firebaseapp.com',
    storageBucket: 'students-database-49778.appspot.com',
    measurementId: 'G-BYR9PS5QNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARUSoiCyp2OsT9mza9KLpDNscwyrF1_3E',
    appId: '1:842796006174:android:5148d1278fb94bfc42e70f',
    messagingSenderId: '842796006174',
    projectId: 'students-database-49778',
    storageBucket: 'students-database-49778.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJFtYi4R1kB7ujgcExsvLI-IdVkfi_gWo',
    appId: '1:842796006174:ios:7769d3950f649bbc42e70f',
    messagingSenderId: '842796006174',
    projectId: 'students-database-49778',
    storageBucket: 'students-database-49778.appspot.com',
    iosClientId: '842796006174-1na88lf4q0s84r7aidrln3ds259ufa8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJFtYi4R1kB7ujgcExsvLI-IdVkfi_gWo',
    appId: '1:842796006174:ios:13e0dc5c0bc4e03142e70f',
    messagingSenderId: '842796006174',
    projectId: 'students-database-49778',
    storageBucket: 'students-database-49778.appspot.com',
    iosClientId: '842796006174-e8mbudnbid5uvo9jp2pckvtvcnqhso5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcai.RunnerTests',
  );
}
